fixes

diff --git a/bin/tfmod b/bin/tfmod
--- a/bin/tfmod
+++ b/bin/tfmod
@@ -20,10 +20,6 @@ function fatal {
   exit 1
 }
 
-function unknown-argument {
-  fatal "unknown argument: ${1}"
-}
-
 # Check if a bin is installed
 
 function has-bin {
@@ -36,17 +32,15 @@ function has-bin {
   return 1
 }
 
-LOG_LEVEL='warn'
+LOG_LEVEL='info'
 ARGV="$*"
 COMMAND=''
 
 while [[ $# -gt 0 ]]; do
   case "${1}" in
     install|remove)
-      if [ -n "${COMMAND}" ]; then
+      if [ -z "${COMMAND}" ]; then
         COMMAND="${1}"
-      else
-        unknown-argument "${1}"
       fi
       shift
       ;;
@@ -56,7 +50,8 @@ while [[ $# -gt 0 ]]; do
       shift
       ;;
     *)
-      unknown-argument "${1}"
+      shift
+      ;;
   esac
 done
 
@@ -165,6 +160,10 @@ function use-package {
   fi
 }
 
+function no-packages {
+  [ ${#PACKAGES[@]} -eq 0 ]
+}
+
 # homebrew based installs
 
 function install-homebrew {
@@ -177,6 +176,8 @@ function install-homebrew {
 }
 
 function brew-install {
+  if no-packages; then return 0; fi
+
   if ! has-bin brew; then
     install-homebrew
   fi
@@ -197,39 +198,37 @@ function brew-install {
 # linux-based installs
 
 function apt-install {
+  if no-packages; then return 0; fi
   sudo apt install "${PACKAGES[@]}"
 }
 
 function dnf-install {
+  if no-packages; then return 0; fi
   sudo dnf install "${PACKAGES[@]}"
 }
 
 # do it up
 
 function install-brew-packages {
-  add-package git
-  add-package python
-  add-package terraform hashicorp/tap/terraform
+  use-package git
+  use-package python
+  use-package terraform hashicorp/tap/terraform
   brew-install
 }
 
 function install-apt-packages {
-  add-package git
-  add-package python3
+  use-package git
+  use-package python3
   apt-install
 }
 
 function install-dnf-packages {
-  add-package git
-  add-package python3
+  use-package git
+  use-package python3
   dnf-install
 }
 
 function install-packages {
-  if [ ${#PACKAGES[@]} -eq 0 ]; then
-    return 1
-  fi
-
   if is-macos; then
     install-brew-packages
   elif has-bin apt; then
@@ -280,7 +279,11 @@ function install-tfmod {
   mkdir -p ~/.local/state
 
   if [ ! -d ~/.local/state/tfmod ]; then
+    info 'installing tfmod to ~/.local/state/tfmod...'
     (cd ~/.local/state && git clone git@github.com:jfhbrook/tfmod.git)
+  else
+    info 'updating tfmod in ~/.local/state/tfmod...'
+    (cd ~/.local/state/tfmod && git pull origin)
   fi
   (cd ~/.local/state/tfmod \
     && terraform -chdir=./modules/tfmod init -upgrade \
@@ -295,4 +298,6 @@ function install {
   install-tfmod
 }
 
-install
+install || fatal 'failed to install tfmod'
+
+info 'congratulations, tfmod is installed!'
